# nombre = input("¿Cúal es tu nombre y apellido? ") 
# apellido = input("¿Cuál es tu nombre y apellido? ")
# print("Hola Sra. ", apellido)
# print("Hola Sra. ", nombre)
nombre = input("¿Cuál es tu nombre? ")
apellido = input("¿Cuál es tu apellido? ")
print("Hola Sra. ", nombre , apellido)